-- This file is autogenerated, please do not make changes to it
package Assert_Sizes is
   Byte_Size : constant Natural := 8;

   Logging_Config_Type_Size : constant Natural := 48;
   String_T_Size : constant Natural := 16;
   Time_Value_Type_Size : constant Natural := 16;
   Account_Info_Type_Size : constant Natural := 4;
   Call_Info_Type_Size : constant Natural := 1376;
   Config_Type_Size : constant Natural := 1704;
   Host_Info_Type_Size : constant Natural := 32;
   Host_Port_Type_Size : constant Natural := 24;
   Transport_Config_Type_Size : constant Natural := 184;

end Assert_Sizes;
